version: "3.9"

services:
  postgres:
    image: postgres
    container_name: go-refresh-pg
    # restart: always
    environment:
      POSTGRES_DB: go-refresh-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
